import type { CampaignSeedInput } from "@/lib/mock-data/campaign-types.seed";

export const campaignSeedsB: CampaignSeedInput[] = [
  {
    id: "hexforge-beta",
    brandId: "brand-hexforge",
    brandName: "Hexforge Games",
    name: "Hexforge Open Beta",
    category: "Gaming",
    status: "ENDING_SOON",
    daysRemaining: 6,
    endsAt: "2026-08-31T23:59:00Z",
    ratePer100kMinor: 4_500,
    budgetMinor: 3_000_000,
    spentPct: 0.73,
    platforms: ["tiktok", "youtube"],
    creatorCount: 289,
    description:
      "Open beta weekend is almost over. Capture squad wipes, world records, and rage quits before servers close Sunday night.",
    rulesSummary:
      "Beta build footage only. Watermark required. Clips expire after the beta window closes.",
  },
  {
    id: "orbit-explainers",
    brandId: "brand-orbit",
    brandName: "Orbit Agency",
    name: "Orbit Explainers",
    category: "Education",
    status: "ACTIVE",
    daysRemaining: 60,
    endsAt: "2026-10-24T23:59:00Z",
    ratePer100kMinor: 2_000,
    budgetMinor: 800_000,
    spentPct: 0.18,
    platforms: ["tiktok", "instagram", "youtube"],
    creatorCount: 94,
    description:
      "Animate one concept per clip from the Orbit Explainer library. Whiteboard energy with zero fluff.",
    rulesSummary:
      "One concept per clip. Cite source material in the caption. No synthetic voiceovers.",
  },
  {
    id: "podium-fm-clips",
    brandId: "brand-podium",
    brandName: "Podium FM",
    name: "Podium FM Clips",
    category: "Podcast",
    status: "ENDING_SOON",
    daysRemaining: 5,
    endsAt: "2026-08-30T23:59:00Z",
    ratePer100kMinor: 5_500,
    budgetMinor: 1_400_000,
    spentPct: 0.69,
    platforms: ["tiktok", "instagram", "x"],
    creatorCount: 176,
    description:
      "The sports debate show that never sleeps. Clip the arguments that will dominate group chats tomorrow morning.",
    rulesSummary:
      "Face-cam crops required. Episode number in caption. No betting references.",
  },
  {
    id: "northbeam-field-notes",
    brandId: "brand-northbeam",
    brandName: "Northbeam Labs",
    name: "Northbeam Field Notes",
    category: "SaaS",
    status: "DRAFT",
    daysRemaining: 90,
    endsAt: "2026-11-23T23:59:00Z",
    ratePer100kMinor: 3_800,
    budgetMinor: 2_200_000,
    spentPct: 0,
    platforms: ["tiktok", "youtube"],
    creatorCount: 0,
    description:
      "Founder-led storytelling clips built from Field Notes essays. Launching to selected creators first.",
    rulesSummary: "Invite-only until public launch. Essay quotes must be verbatim.",
  },
  {
    id: "midnight-reel-club",
    brandId: "brand-lumen",
    brandName: "Lumen Audio",
    name: "Midnight Reel Club",
    category: "Entertainment",
    status: "ACTIVE",
    daysRemaining: 18,
    endsAt: "2026-09-12T23:59:00Z",
    ratePer100kMinor: 3_200,
    budgetMinor: 1_600_000,
    spentPct: 0.51,
    platforms: ["tiktok", "instagram", "youtube", "x"],
    creatorCount: 233,
    description:
      "Late-night variety shorts: street interviews, hidden-camera bits, and reaction formats from the Midnight archive.",
    rulesSummary:
      "Blur bystander faces. Original captions only. No splicing that changes context.",
  },
  {
    id: "lumen-audio-drops",
    brandId: "brand-lumen",
    brandName: "Lumen Audio",
    name: "Lumen Audio Drops",
    category: "Music",
    status: "ENDING_SOON",
    daysRemaining: 9,
    endsAt: "2026-09-03T23:59:00Z",
    ratePer100kMinor: 4_800,
    budgetMinor: 1_200_000,
    spentPct: 0.58,
    platforms: ["instagram", "tiktok"],
    creatorCount: 121,
    description:
      "Every Friday a new single drops. Be first to use the sound and ride the trend wave through the weekend.",
    rulesSummary:
      "Official sound only. First-use creators get boosted rates. No lyric edits.",
  },
];
